import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";
import { useRouter } from "next/router";

import useFeedRecent from "../../../hooks/use-feed-recent";

const SinglePageView = () => {
  const router = useRouter();
  const { id } = router.query;
  console.log({ id });
  const { format: queryFormat } = router.query;
  const format = queryFormat || "html";

  console.log({ format });

  const url = `http://localhost:3001/api/data?author=${id}`;

  // const dataJSON = data.json();

  // console.log({dataJSON})
  const { feed } = useFeedRecent(id);
  console.log(feed);

  return (
    <div className={styles.container}>
      <Head>
        <title>blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}></h1>

        {format &&
          format === "html" && (
            <div>
              <h1>Feed for {id}</h1>
                {feed?.map((item) => {
                  return <div key={item.id}>
                    <span className="text-white">{item.data}</span>
                  </div>
                })}
            </div>
          )}

        {format && format === "json" && (
          <pre>{JSON.stringify(feed, null, 2)}</pre>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>powered by caffeine</span>
        </a>
      </footer>
    </div>
  );
};

export default SinglePageView;
